#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
_SUB_ROOT="$(abs_dirname "$libexec_path")"
_LOCAL_SUB_ROOT=
bin_path="${libexec_path}"
local_root="$PWD/.sub/libexec"

if [ -d "$local_root" ]; then
  _LOCAL_SUB_ROOT="$(abs_dirname "${local_root}/")"
  bin_path="${bin_path}:${_LOCAL_SUB_ROOT}"
fi

export _SUB_ROOT _LOCAL_SUB_ROOT
export ORIG_PATH="$PATH"
export PATH="${bin_path}:${PATH}"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec sub-help
  ;;
* )
  command_path="$(command -v "sub-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "sub: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
