#!/usr/bin/env bash
set -e

command_path() {
  command -v "sub-$command" || command -v "sub-sh-$command" || true
}

summary() {
  sed -n "s/^[#;];* Summary: \(.*\)/\1/p" "$1" | head -n1
}

# Only zsh completions calls this
print_summaries() {
  for command in $(sub-commands); do
    local file="$(command_path "$command")"
    if [ ! -h "$file" ]; then
      local summary="$(summary "$file")"
      if [ -n "$summary" ]; then
        printf "%s[%s]\n" "$command" "$summary"
      else
        echo "$command"
      fi
    fi
  done
}

command="$1"
if [ "$command" = "--commands" ]; then
  print_summaries
  exit
fi

if [ -z "$command" ]; then
  echo "usage: sub completions command [arg1 arg2...]" >&2
  exit 1
fi

file_path="$(command_path "$command")"
if [ -n "$file_path" ]; then
  if grep "\--complete" "$file_path" >/dev/null; then
    shift
    exec "$file_path" --complete "$@"
  fi
fi
