#!/usr/bin/env bash
# Usage: sub source <command>
# Summary: Output source of sub command <command>

if [ "$1" = "--complete" ]; then
  exec sub-commands
fi

if [ -z "$1" ]; then
  echo "Please provide a command name" >&2
  exit 1
fi

command_path() {
  command -v "sub-$1" || command -v "sub-sh-$1" || true
}

path="$(command_path $1)"

output=

if command -v bat >/dev/null; then
    output="bat"
elif [ -n "$PAGER" ]; then
    output="$PAGER"
else
    output="cat"
fi

if [[ -n "$path" ]]; then
  exec $output $path
else
  echo "Could not find command $1" >&2
  exit 1
fi
